USE Test
GO

EXEC sp_who2 ACTIVE

KILL 57

ALTER DATABASE Test SET MULTI_USER

ALTER DATABASE Test SET OFFLINE

ALTER DATABASE Test SET SINGLE_USER WITH ROLLBACK IMMEDIATE

ALTER DATABASE Test SET  MULTI_USER WITH NO_WAIT
GO
DBCC CHECKDB ('Test', REPAIR_ALLOW_DATA_LOSS)

SELECT request_session_id FROM sys.dm_tran_locks 

WHERE resource_database_id = DB_ID('Test') 

KILL 51