USE master
GO
CREATE MASTER KEY ENCRYPTION
BY PASSWORD = 'Honda_888'
GO

CREATE CERTIFICATE TDE_cert
WITH SUBJECT = 'Test TDE cert'
GO

CREATE DATABASE TDE_Test
GO

USE TDE_Test
GO

CREATE DATABASE ENCRYPTION KEY 
WITH ALGORITHM = AES_256
ENCRYPTION BY SERVER CERTIFICATE TDE_cert

ALTER DATABASE TDE_Test
SET ENCRYPTION ON
GO

USE master
GO

BACKUP CERTIFICATE TDE_cert
TO FILE = 'C:\SQL\TDE_cert'
WITH PRIVATE KEY (FILE = 'C:\SQL\TDE_cert.pvk'
, ENCRYPTION BY PASSWORD = 'Honda_888')
